###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2022. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# Needed DBs: ICN GCD CLOS

apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 22.0.1

spec:
  appVersion: 22.0.1
  ibm_license: accept

  shared_configuration:
    show_sensitive_log: true
    no_log: false

    sc_deployment_fncm_license: "non-production"
    sc_deployment_baw_license: "non-production"
    sc_deployment_license: "non-production"

    sc_image_repository: cp.icr.io
    root_ca_secret: icp4a-root-ca
    external_tls_certificate_secret: tlsSecretName

    sc_deployment_patterns: "foundation,content"
    sc_optional_components: "css,cmis"

    sc_deployment_context: "CP4A"
    sc_deployment_type: "Production"
    sc_deployment_platform: "cp4baDeploymentPlatform"
    sc_deployment_hostname_suffix: "{{ meta.namespace }}.cp4baOcpHostname"
    sc_install_automation_base: true

    sc_ingress_enable: false
    sc_ingress_tls_secret_name: tlsSecretName
    trusted_certificate_list:
      trustedCertificateList

    storage_configuration:
      sc_slow_file_storage_classname: cp4baScSlow
      sc_medium_file_storage_classname: cp4baScMedium
      sc_fast_file_storage_classname: cp4baScFast
      sc_block_storage_classname: cp4baBlockScFast

    sc_cpe_limited_storage: false
    sc_run_as_user:

    images:
      keytool_job_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-jobcontainer
        tag: 22.0.1-IF002
      dbcompatibility_init_container:
        repository: cp.icr.io/cp/cp4a/aae/dba-dbcompatibility-initcontainer
        tag: 22.0.1-IF002
      keytool_init_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-initcontainer
        tag: 22.0.1-IF002
      umsregistration_initjob:
        repository: cp.icr.io/cp/cp4a/aae/dba-umsregistration-initjob
        tag: 22.0.1-IF002
      pull_policy: IfNotPresent

    encryption_key_secret: icp4a-shared-encryption-key

    sc_content_initialization: true
    sc_content_verification: false

    image_pull_secrets:
      - admin.registrykey

  ldap_configuration:
    lc_selected_ldap_type: "ldapType"
    lc_ldap_server: "ldapServer"
    lc_ldap_port: "ldapPort"
    lc_bind_secret: ldap-bind-secret
    lc_ldap_base_dn: "ldapBaseDn"
    lc_ldap_ssl_enabled: false
    lc_ldap_user_name_attribute: "ldapUserNameAttribute"
    lc_ldap_user_display_name_attr: "ldapUserDisplayNameAttr"
    lc_ldap_group_base_dn: "ldapGroupBaseDn"
    lc_ldap_group_name_attribute: "ldapGroupNameAttribute"
    lc_ldap_group_display_name_attr: "ldapGroupDisplayNameAttr"
    lc_ldap_group_membership_search_filter: "ldapGroupMembershipSearchFilter"
    lc_ldap_group_member_id_map: "ldapGroupMemberIdMap"
    lc_ldap_recursive_search: false
    lc_ldap_max_search_results: 4500
    tds:
      lc_user_filter: "ldapTdsUserFilter"
      lc_group_filter: "ldapTdsGroupFilter"

  datasource_configuration:
    dc_ssl_enabled: false

    dc_icn_datasource:
      dc_database_type: "db2"
      dc_common_icn_datasource_name: "ECMClientDS"
      database_servername: "db2HostName"
      database_port: "db2PortNumber"
      database_name: "db2IcndbName"
      connection_manager:
        min_pool_size: 0
        max_pool_size: 100
        max_idle_time: 1m
        reap_time: 2m
        purge_policy: EntirePool

    dc_gcd_datasource:
      dc_database_type: "db2"
      dc_common_gcd_datasource_name: "FNGCDDS"
      dc_common_gcd_xa_datasource_name: "FNGCDDSXA"
      database_servername: "db2HostName"
      database_name: "db2GcddbName"
      database_port: "db2PortNumber"
      connection_manager:
        min_pool_size: 0
        max_pool_size: 100
        max_idle_time: 1m
        reap_time: 2m
        purge_policy: EntirePool

    dc_os_datasources:
      - dc_database_type: "db2"
        dc_os_label: "clos"
        dc_common_os_datasource_name: "CLOSDS"
        dc_common_os_xa_datasource_name: "CLOSDSXA"
        database_servername: "db2HostName"
        database_name: "db2ClosName"
        database_port: "db2PortNumber"

  ##################################################################
  ########   Resource Registry configuration                ########
  ##################################################################
  resource_registry_configuration:
#    hostname: "rr-{{ shared_configuration.sc_deployment_hostname_suffix }}"
#    port: 443
    images:
      pull_policy: IfNotPresent
      resource_registry:
        repository: cp.icr.io/cp/cp4a/aae/dba-etcd
        tag: 22.0.1-IF002
    admin_secret_name: resource-registry-admin-secret
    replica_size: 3
    probe:
      liveness:
        initial_delay_seconds: 60
        period_seconds: 10
        timeout_seconds: 5
        success_threshold: 1
        failure_threshold: 3
      readiness:
        initial_delay_seconds: 10
        period_seconds: 10
        timeout_seconds: 5
        success_threshold: 1
        failure_threshold: 3
    resource:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    auto_backup:
      enable: true
      minimal_time_interval: 300
      pvc_name: "{{ meta.name }}-dba-rr-pvc"
      log_pvc_name: 'cp4a-shared-log-pvc'
      dynamic_provision:
        enable: true
        size: 3Gi
        size_for_logstore:
        storage_class: "{{ shared_configuration.storage_configuration.sc_fast_file_storage_classname }}"

  ########################################################################
  ########   IBM Business Automation Navigator configuration      ########
  ########################################################################
  navigator_configuration:
    ban_secret_name: ibm-ban-secret
    ban_ext_tls_secret_name: tlsSecretName

    arch:
      amd64: "3 - Most preferred"

    replica_count: cp4baReplicaCount

    image:
      repository: cp.icr.io/cp/cp4a/ban/navigator-sso
      tag: ga-3011-icn-if002
      pull_policy: IfNotPresent

    log:
      format: json

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1536Mi

    auto_scaling:
      enabled: false
      max_replicas: 2
      min_replicas: 2
      target_cpu_utilization_percentage: 80

    icn_production_setting:
      timezone: Etc/UTC
      jvm_initial_heap_percentage: 40
      jvm_max_heap_percentage: 66

      jvm_customize_options:

      icn_jndids_name: ECMClientDS
      icn_schema: db2IcndbName
      icn_table_space: db2IcndbName
      allow_remote_plugins_via_http: false

    monitor_enabled: false
    logging_enabled: false

    datavolume:
      existing_pvc_for_icn_cfgstore: "icn-cfgstore"
      existing_pvc_for_icn_logstore: "icn-logstore"
      existing_pvc_for_icn_pluginstore: "icn-pluginstore"
      existing_pvc_for_icnvw_cachestore: "icn-vw-cachestore"
      existing_pvc_for_icnvw_logstore: "icn-vw-logstore"
      existing_pvc_for_icn_aspera: "icn-asperastore"

    probe:
      readiness:
        initial_delay_seconds: 120
        period_seconds: 5
        timeout_seconds: 10
        failure_threshold: 6
      liveness:
        initial_delay_seconds: 600
        period_seconds: 5
        timeout_seconds: 5
        failure_threshold: 6

  ########################################################################
  ########      IBM FileNet Content Manager configuration         ########
  ########################################################################
  ecm_configuration:
    fncm_secret_name: ibm-fncm-secret
    fncm_ext_tls_secret_name: tlsSecretName
    route_ingress_annotations:

    ####################################
    ## Start of configuration for CPE ##
    ####################################
    cpe:
      arch:
        amd64: "3 - Most preferred"

      replica_count: cp4baReplicaCount

      image:
        repository: cp.icr.io/cp/cp4a/fncm/cpe
        tag: ga-558-p8cpe-la005
        pull_policy: IfNotPresent

      log:
       format: json

      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 3072Mi

      auto_scaling:
        enabled: false
        max_replicas: 2
        min_replicas: 2
        target_cpu_utilization_percentage: 80

      cpe_production_setting:
        time_zone: Etc/UTC
        jvm_initial_heap_percentage: 18
        jvm_max_heap_percentage: 33
        jvm_customize_options:

        gcd_jndi_name: FNGCDDS
        gcd_jndixa_name: FNGCDDSXA
        license_model: FNCM.PVUNonProd
        license: accept
        disable_fips: false

      monitor_enabled: false
      logging_enabled: false

      collectd_enable_plugin_write_graphite: false

      datavolume:
        existing_pvc_for_cpe_cfgstore: "cpe-cfgstore"
        existing_pvc_for_cpe_logstore: "cpe-logstore"
        existing_pvc_for_cpe_filestore: "cpe-filestore"
        existing_pvc_for_cpe_icmrulestore: "cpe-icmrulesstore"
        existing_pvc_for_cpe_textextstore: "cpe-textextstore"
        existing_pvc_for_cpe_bootstrapstore: "cpe-bootstrapstore"
        existing_pvc_for_cpe_fnlogstore: "cpe-fnlogstore"

      probe:
        readiness:
          initial_delay_seconds: 180
          period_seconds: 30
          timeout_seconds: 10
          failure_threshold: 6
        liveness:
          initial_delay_seconds: 600
          period_seconds: 30
          timeout_seconds: 5
          failure_threshold: 6

    ####################################
    ## Start of configuration for CSS ##
    ####################################
    css:
      arch:
        amd64: "3 - Most preferred"

      replica_count: 1

      image:
        repository: cp.icr.io/cp/cp4a/fncm/css
        tag: ga-558-p8css-la005
        pull_policy: IfNotPresent

      log:
        format: json

      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 4096Mi

      css_production_setting:
        jvm_max_heap_percentage: 50
        license: accept

      monitor_enabled: false
      logging_enabled: false
      collectd_enable_plugin_write_graphite: false

      datavolume:
        existing_pvc_for_css_cfgstore: "css-cfgstore"
        existing_pvc_for_css_logstore: "css-logstore"
        existing_pvc_for_css_tmpstore: "css-tempstore"
        existing_pvc_for_index: "css-indexstore"
        existing_pvc_for_css_customstore: "css-customstore"

      probe:
        readiness:
          initial_delay_seconds: 60
          period_seconds: 10
          timeout_seconds: 10
          failure_threshold: 6
        liveness:
          initial_delay_seconds: 180
          period_seconds: 10
          timeout_seconds: 5
          failure_threshold: 6

    #####################################
    ## Start of configuration for CMIS ##
    #####################################
    cmis:
      arch:
        amd64: "3 - Most preferred"

      replica_count: cp4baReplicaCount

      image:
        repository: cp.icr.io/cp/cp4a/fncm/cmis
        tag: ga-306-cmis-la104
        pull_policy: IfNotPresent

      log:
        format: json

      resources:
        requests:
          cpu: 500m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1536Mi

      auto_scaling:
        enabled: false
        max_replicas: 2
        min_replicas: 2
        target_cpu_utilization_percentage: 80

      cmis_production_setting:
        cpe_url:
        time_zone: Etc/UTC
        jvm_initial_heap_percentage: 40
        jvm_max_heap_percentage: 66
        jvm_customize_options:

        disable_fips: false
        ws_security_enabled: false
        checkout_copycontent: true
        default_maxitems: 25

        cvl_cache: true
        secure_metadata_cache: false
        filter_hidden_properties: true
        querytime_limit: 180
        resumable_queries_forrest: true
        escape_unsafe_string_characters: false
        max_soap_size: 180
        print_pull_stacktrace: false
        folder_first_search: false
        ignore_root_documents: false
        supporting_type_mutability: false

        license: accept

      monitor_enabled: false
      logging_enabled: false
      collectd_enable_plugin_write_graphite: false

      datavolume:
        existing_pvc_for_cmis_cfgstore: "cmis-cfgstore"
        existing_pvc_for_cmis_logstore: "cmis-logstore"

      probe:
        readiness:
          initial_delay_seconds: 90
          period_seconds: 10
          timeout_seconds: 10
          failure_threshold: 6
        liveness:
          initial_delay_seconds: 180
          period_seconds: 10
          timeout_seconds: 5
          failure_threshold: 6

    ########################################
    ## Start of configuration for GraphQL ##
    ########################################
    graphql:
      arch:
        amd64: "3 - Most preferred"

      replica_count: cp4baReplicaCount

      image:
        repository: cp.icr.io/cp/cp4a/fncm/graphql
        tag: ga-558-p8cgql-la005
        pull_policy: IfNotPresent

      log:
        format: json

      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1536Mi

      auto_scaling:
        enabled: false
        min_replicas: 2
        max_replicas: 2
        target_cpu_utilization_percentage: 80

      graphql_production_setting:
        time_zone: Etc/UTC
        jvm_initial_heap_percentage: 40
        jvm_max_heap_percentage: 66
        jvm_customize_options:

        license_model: FNCM.PVUNonProd
        license: accept
        enable_graph_iql: true
        cpe_uri:

      monitor_enabled: false
      logging_enabled: false
      collectd_enable_plugin_write_graphite: false

      datavolume:
        existing_pvc_for_graphql_cfgstore: "graphql-cfgstore"
        existing_pvc_for_graphql_logstore: "graphql-logstore"

      probe:
        readiness:
          initial_delay_seconds: 120
          period_seconds: 10
          timeout_seconds: 10
          failure_threshold: 6
        liveness:
          initial_delay_seconds: 600
          period_seconds: 10
          timeout_seconds: 5
          failure_threshold: 6

  ########################################################################
  ######## IBM FileNet Content Manager Initialization configuration ######
  ########################################################################
  initialize_configuration:
    ic_domain_creation:
      domain_name: "CP4BADOM"
      encryption_key: "128"

    ic_ldap_creation:
      ic_ldap_admin_user_name:
        - "cp4baAdminName"
      ic_ldap_admins_groups_name:
        - "cp4baAdminGroup"
      ic_ldap_name: "ldapName"

    ic_obj_store_creation:
      object_stores:
        - oc_cpe_obj_store_display_name: "db2ClosName"
          oc_cpe_obj_store_symb_name: "db2ClosName"
          oc_cpe_obj_store_conn:
            dc_os_datasource_name: "CLOSDS"
            dc_os_xa_datasource_name: "CLOSDSXA"
          oc_cpe_obj_store_admin_user_groups:
            - "cp4baAdminGroup"
            - "cp4baAdminName"
          oc_cpe_obj_store_basic_user_groups:
            - "cp4baUsersGroup"
          oc_cpe_obj_store_enable_content_event_emitter: false
